services:
  cassandra1:
    image: cassandra:4.1.5
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    volumes:
      - cassandra1_data:/var/lib/cassandra
    networks:
      - cassandra-network
    ports:
      - "9042:9042"

volumes:
  cassandra1_data:

networks:
  cassandra-network:
    driver: bridge
